forwards:
- dest:
  - -1001335239206
  end: null
  offset: '168'
  source: -1001102011551
live:
  delete_on_edit: null
  delete_sync: false
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
show_forwarded_from: false
