forwards:
  - source: -1001102011551
    dest: [-1001335239206]
    offset: 45
past:
  delay: 3 # wait for 3s after forwarding each message

show_forwarded_from: false



plugins:
  # specify the plugins you want to use
  filter:
    text:
      blacklist: ["badword"]

# read full documentation of plugins here https://git.io/J3NuC

##########################

# make sure you understand the configuration before you run
# edit this file to suit your needs
# read more here https://github.com/aahnik/tgcf
